[package]
name = "plc"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "plc-server"
path = "bin/server.rs"

[dependencies]
openssl-sys = { version = "0.9.102", features = ["vendored"] }
paho-mqtt = "0.12.5"
rocket = "0.5.1"
